apiVersion: v1
kind: Pod
metadata:
  name: udagram-frontend
spec:
  containers:
  - name: app
    image: kwamito/udagram-frontend
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator
    image: kwamito/udagram-frontend
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"