name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push user api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kwamito/udagram-user:latest

      -

        name: Build and push feed api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kwamito/udagram-feed:latest

      -

        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kwamito/udagram-frontend:latest